No need to escape multiline runs

diff --git a/.github/workflows/version-checker.yml b/.github/workflows/version-checker.yml
--- a/.github/workflows/version-checker.yml
+++ b/.github/workflows/version-checker.yml
@@ -18,13 +18,13 @@ jobs:
 
       - name: Get Versions from this repos
         run: |
-          FAMILY_L=$(echo "${{matrix.family}}" | tr '[:upper:]' '[:lower:]'); \
-          family_src_file=${GITHUB_WORKSPACE}/cmake/stm32/${FAMILY_L}.cmake; \
-          cube_version=$(sed -rn 's@set\(CUBE_${{matrix.family}}_VERSION(\s+)(.*)\)@\2@p' ${family_src_file}); \
-          echo "Cube version: ${cube_version}"; \
-          cmsis_version=$(sed -rn 's@set\(CMSIS_${{matrix.family}}_VERSION(\s+)(.*)\)@\2@p' ${family_src_file}); \
-          echo "CMSIS version: ${cmsis_version}"; \
-          hal_version=$(sed -rn 's@set\(HAL_${{matrix.family}}_VERSION(\s+)(.*)\)@\2@p' ${family_src_file}); \
+          FAMILY_L=$(echo "${{matrix.family}}" | tr '[:upper:]' '[:lower:]');
+          family_src_file=${GITHUB_WORKSPACE}/cmake/stm32/${FAMILY_L}.cmake;
+          cube_version=$(sed -rn 's@set\(CUBE_${{matrix.family}}_VERSION(\s+)(.*)\)@\2@p' ${family_src_file});
+          echo "Cube version: ${cube_version}";
+          cmsis_version=$(sed -rn 's@set\(CMSIS_${{matrix.family}}_VERSION(\s+)(.*)\)@\2@p' ${family_src_file});
+          echo "CMSIS version: ${cmsis_version}";
+          hal_version=$(sed -rn 's@set\(HAL_${{matrix.family}}_VERSION(\s+)(.*)\)@\2@p' ${family_src_file});
           echo "HAL version: ${cmsis_version}";
 
       - name: Get Cube version
@@ -34,13 +34,13 @@ jobs:
             --url "https://api.github.com/repos/STMicroelectronics/STM32Cube${{matrix.family}}/tags" \
             --header "Accept: application/vnd.github+json" \
             --header "Authorization: Bearer $GH_TOKEN" \
-            -o body.json ); \
-          if [ "${http_code}" -ne "200" ]; then \
-            echo "Failed (${http_code}) to get https://api.github.com/repos/STMicroelectronics/STM32Cube${{matrix.family}}/tags"; \
-            exit 1; \
-          else \
-            latest_cube_version=$(jq '.[0].name' body.json | sed -rn 's@\"@@gp' ); \
-            echo "Latest Cube Version: ${latest_cube_version}"; \
+            -o body.json );
+          if [ "${http_code}" -ne "200" ]; then
+            echo "Failed (${http_code}) to get https://api.github.com/repos/STMicroelectronics/STM32Cube${{matrix.family}}/tags";
+            exit 1;
+          else
+            latest_cube_version=$(jq '.[0].name' body.json | sed -rn 's@\"@@gp' );
+            echo "Latest Cube Version: ${latest_cube_version}";
           fi
 
       - name: Get CMSIS version
@@ -51,13 +51,13 @@ jobs:
             --header "Accept: application/vnd.github+json" \
             --header "Authorization: Bearer $GH_TOKEN" \
             -o body.json ); \
-          if [ "${http_code}" -ne "200" ]; then \
-            echo "Failed (${http_code}) to get https://api.github.com/repos/STMicroelectronics/cmsis_device_${FAMILY_L}/tags"; \
-            echo "Assume we can use the one from cube"; \
-            latest_cmsis_version="cube"; \
-          else \
-            latest_cmsis_version=$(jq '.[0].name' body.json | sed -rn 's@\"@@gp' ); \
-          fi \
+          if [ "${http_code}" -ne "200" ]; then
+            echo "Failed (${http_code}) to get https://api.github.com/repos/STMicroelectronics/cmsis_device_${FAMILY_L}/tags";
+            echo "Assume we can use the one from cube";
+            latest_cmsis_version="cube";
+          else
+            latest_cmsis_version=$(jq '.[0].name' body.json | sed -rn 's@\"@@gp' );
+          fi
           echo "Latest CMSIS Version: ${latest_cmsis_version}";
 
       - name: Get HAL version
@@ -68,11 +68,11 @@ jobs:
             --header "Accept: application/vnd.github+json" \
             --header "Authorization: Bearer $GH_TOKEN" \
             -o body.json ); \
-          if [ "${http_code}" -ne "200" ]; then \
-            echo "Failed (${http_code}) to get https://api.github.com/repos/STMicroelectronics/stm32${FAMILY_L}xx_hal_driver/tags"; \
-            echo "Assume we can use the one from cube"; \
-            latest_hal_version="cube"; \
-          else \
-            latest_hal_version=$(jq '.[0].name' body.json | sed -rn 's@\"@@gp' ); \
-          fi \
+          if [ "${http_code}" -ne "200" ]; then
+            echo "Failed (${http_code}) to get https://api.github.com/repos/STMicroelectronics/stm32${FAMILY_L}xx_hal_driver/tags";
+            echo "Assume we can use the one from cube";
+            latest_hal_version="cube";
+          else
+            latest_hal_version=$(jq '.[0].name' body.json | sed -rn 's@\"@@gp' );
+          fi
           echo "Latest HAL Version: ${latest_hal_version}";
